<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pharmacy Report</title>
    <style>
        @page { size: A4; margin: 16mm; }
        body { margin: 0; font-family: Arial, sans-serif; color: #0f172a; font-size: 12px; }
        h1 { margin: 0; font-size: 20px; }
        .sub { margin-top: 6px; color: #475569; }
        .meta { margin: 10px 0; }
        table { width: 100%; border-collapse: collapse; font-size: 11px; }
        th, td { border: 1px solid #e2e8f0; padding: 5px; text-align: left; vertical-align: top; }
        th { background: #f8fafc; text-transform: uppercase; letter-spacing: 0.06em; color: #475569; }
    </style>
</head>
<body>
    <h1>KORT Burn Center - Pharmacy {{ ucfirst($filters['period']) }} Report</h1>
    <p class="sub">{{ $filters['date_from'] }} to {{ $filters['date_to'] }}</p>
    <p class="meta">
        Total Qty: {{ $summary['total_dispensed_quantity'] }} |
        Records: {{ $summary['total_records'] }} |
        Patients: {{ $summary['patients_covered'] }} |
        Medicines: {{ $summary['medicines_covered'] }}
    </p>
    <table>
        <thead>
            <tr>
                <th>Dispensed At</th>
                <th>Patient</th>
                <th>Prescription</th>
                <th>Doctor</th>
                <th>Pharmacist</th>
                <th>Medicine</th>
                <th>Batch</th>
                <th>Expiry</th>
                <th>Qty</th>
                <th>Unit</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($rows as $row)
                <tr>
                    <td>{{ optional($row->dispensing?->dispensed_at)->format('d M Y h:i A') }}</td>
                    <td>{{ $row->dispensing?->patient?->full_name }}</td>
                    <td>{{ $row->dispensing?->prescription?->prescription_number }}</td>
                    <td>{{ $row->dispensing?->prescription?->visit?->doctor?->name }}</td>
                    <td>{{ $row->dispensing?->pharmacist?->name }}</td>
                    <td>{{ $row->inventoryItem?->item_name ?: $row->prescriptionItem?->medicine_name }}</td>
                    <td>{{ $row->batch_number }}</td>
                    <td>{{ optional($row->expiry_date)->format('d M Y') }}</td>
                    <td>{{ $row->dispensed_quantity }}</td>
                    <td>{{ $row->unit_of_measure }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <p class="sub">Generated by {{ $generatedBy?->name ?: 'System' }} at {{ $generatedAt->format('d M Y h:i A') }}</p>
</body>
</html>

