<?php

namespace App\Support;

class PermissionRegistry
{
    public static function groups(): array
    {
        return [
            'Dashboard' => [
                'dashboard.view' => 'Access role-based dashboards.',
            ],
            'Users' => [
                'users.view' => 'View user accounts and staff directory details.',
                'users.create' => 'Create new user accounts.',
                'users.update' => 'Update user profile, department, and access details.',
                'users.delete' => 'Deactivate or delete user accounts.',
                'users.assign-roles' => 'Assign or change user roles.',
            ],
            'Roles & Permissions' => [
                'roles.view' => 'Review role definitions and permission coverage.',
                'roles.create' => 'Create custom roles.',
                'roles.update' => 'Update role permissions.',
            ],
            'Departments' => [
                'departments.view' => 'View hospital departments and burn center units.',
                'departments.create' => 'Create departments.',
                'departments.update' => 'Update departments.',
                'departments.delete' => 'Archive departments.',
            ],
            'Locations' => [
                'locations.view' => 'View wards, stores, and room locations.',
                'locations.create' => 'Create locations.',
                'locations.update' => 'Update locations.',
                'locations.delete' => 'Archive locations.',
            ],
            'Asset Categories' => [
                'asset-category.view' => 'View asset categories.',
                'asset-category.create' => 'Create asset categories.',
                'asset-category.edit' => 'Edit asset categories.',
                'asset-category.delete' => 'Archive asset categories.',
            ],
            'Asset Registry' => [
                'asset.view' => 'View asset registry records.',
                'asset.create' => 'Create asset registry records.',
                'asset.edit' => 'Edit asset registry records.',
                'asset.delete' => 'Archive asset records.',
            ],
            'Asset Tags' => [
                'asset-tag.view' => 'View asset tag details and print history.',
                'asset-tag.generate' => 'Generate asset tags.',
                'asset-tag.bulk-generate' => 'Generate tags in bulk.',
                'asset-tag.print' => 'Print and reprint asset labels.',
                'asset-tag.regenerate' => 'Regenerate retired asset tags.',
            ],
            'Asset Workflows' => [
                'asset.scan' => 'Scan or search asset codes and tags.',
                'asset-issue.view' => 'Review issue workflow screens.',
                'asset-issue.create' => 'Issue assets to users or locations.',
                'asset-return.view' => 'Review return workflow screens.',
                'asset-return.create' => 'Return issued assets.',
                'asset-transfer.view' => 'Review transfer workflow screens.',
                'asset-transfer.create' => 'Transfer assets between custodians or locations.',
                'asset-history.view' => 'View full asset movement and status history.',
                'asset-status.change' => 'Change asset status and condition.',
            ],
            'Assets' => [
                'assets.view' => 'View asset records.',
                'assets.create' => 'Create asset records.',
                'assets.update' => 'Update asset details.',
                'assets.assign' => 'Issue assets to staff or departments.',
                'assets.transfer' => 'Transfer assets between departments and locations.',
                'assets.return' => 'Receive returned assets.',
                'assets.condemn' => 'Condemn or dispose assets.',
                'asset-labels.generate' => 'Generate barcode and QR labels.',
                'asset-labels.print' => 'Print or reprint asset labels.',
            ],
            'Inventory Categories' => [
                'inventory-category.view' => 'View inventory categories and supply groupings.',
                'inventory-category.create' => 'Create inventory categories.',
                'inventory-category.edit' => 'Edit inventory categories.',
                'inventory-category.delete' => 'Archive inventory categories.',
            ],
            'Inventory Items' => [
                'inventory-item.view' => 'View inventory items, batches, and balances.',
                'inventory-item.create' => 'Create inventory items.',
                'inventory-item.edit' => 'Edit inventory items.',
                'inventory-item.delete' => 'Archive inventory items.',
                'inventory-item.scan' => 'Scan item barcodes and batch lookups.',
            ],
            'Inventory Stock Workflows' => [
                'stock-receipt.view' => 'View stock receipt records.',
                'stock-receipt.create' => 'Receive stock into store locations.',
                'stock-issue.view' => 'View stock issue records.',
                'stock-issue.create' => 'Issue stock to departments, rooms, and staff.',
                'stock-return.view' => 'View stock return records.',
                'stock-return.create' => 'Receive unused or damaged stock returns.',
                'stock-transfer.view' => 'View stock transfer records.',
                'stock-transfer.create' => 'Transfer stock between stores and locations.',
                'stock-adjustment.view' => 'View stock adjustment records.',
                'stock-adjustment.create' => 'Create stock adjustments.',
                'stock-adjustment.approve' => 'Approve sensitive stock adjustments.',
            ],
            'Inventory Governance' => [
                'inventory-ledger.view' => 'View the inventory movement ledger and batch history.',
                'stock-quarantine.manage' => 'Quarantine and release unsafe stock.',
                'stock-expiry.manage' => 'Mark and manage expired stock.',
                'stock-damage.manage' => 'Mark damaged stock and isolate unsafe batches.',
            ],
            'Suppliers' => [
                'supplier.view' => 'View supplier master data and procurement contacts.',
                'supplier.create' => 'Create suppliers.',
                'supplier.edit' => 'Edit suppliers.',
                'supplier.delete' => 'Archive suppliers.',
            ],
            'Procurement Requisitions' => [
                'requisition.view' => 'View purchase requisitions.',
                'requisition.create' => 'Create purchase requisitions.',
                'requisition.edit' => 'Edit draft requisitions.',
                'requisition.submit' => 'Submit requisitions for approval.',
                'requisition.approve' => 'Approve requisitions at the assigned approval stage.',
                'requisition.reject' => 'Reject requisitions with reason.',
                'requisition.cancel' => 'Cancel requisitions when permitted.',
                'procurement-approval.view' => 'View procurement approval history and routing.',
            ],
            'Purchase Orders' => [
                'purchase-order.view' => 'View purchase orders.',
                'purchase-order.create' => 'Create purchase orders.',
                'purchase-order.edit' => 'Edit draft purchase orders.',
                'purchase-order.issue' => 'Issue approved purchase orders to suppliers.',
                'purchase-order.cancel' => 'Cancel purchase orders.',
                'purchase-order.close' => 'Close completed purchase orders.',
            ],
            'Goods Receipts' => [
                'goods-receipt.view' => 'View goods receipt notes and discrepancies.',
                'goods-receipt.create' => 'Create goods receipt notes.',
                'goods-receipt.process' => 'Process accepted and rejected goods into assets or inventory.',
            ],
            'Biomedical & Maintenance' => [
                'maintenance.view' => 'View maintenance plans and tickets.',
                'maintenance.manage' => 'Manage preventive and corrective maintenance.',
                'maintenance.fit-certify' => 'Mark assets fit or unfit for use.',
                'calibrations.manage' => 'Manage calibration schedules and records.',
                'faults.report' => 'Report equipment faults and downtime.',
            ],
            'Reports' => [
                'reports.view' => 'View management and operational reports.',
                'reports.export' => 'Export PDF, Excel, and CSV reports.',
            ],
            'Audit Logs' => [
                'audit-logs.view' => 'View full activity and compliance logs.',
            ],
            'Settings' => [
                'settings.view' => 'View system settings.',
                'settings.update' => 'Update system settings.',
            ],
        ];
    }

    public static function all(): array
    {
        return array_keys(array_merge(...array_values(self::groups())));
    }

    public static function roleMatrix(): array
    {
        return [
            'Super Admin' => self::all(),
            'Hospital Admin' => [
                'dashboard.view',
                'users.view',
                'users.create',
                'users.update',
                'users.assign-roles',
                'roles.view',
                'roles.update',
                'departments.view',
                'departments.create',
                'departments.update',
                'locations.view',
                'locations.create',
                'locations.update',
                'asset-category.view',
                'asset-category.create',
                'asset-category.edit',
                'asset-category.delete',
                'asset.view',
                'asset.create',
                'asset.edit',
                'asset.delete',
                'asset-tag.view',
                'asset-tag.generate',
                'asset-tag.bulk-generate',
                'asset-tag.print',
                'asset-tag.regenerate',
                'asset.scan',
                'asset-issue.view',
                'asset-issue.create',
                'asset-return.view',
                'asset-return.create',
                'asset-transfer.view',
                'asset-transfer.create',
                'asset-history.view',
                'asset-status.change',
                'assets.view',
                'assets.create',
                'assets.update',
                'assets.assign',
                'assets.transfer',
                'assets.return',
                'asset-labels.generate',
                'asset-labels.print',
                'inventory-category.view',
                'inventory-category.create',
                'inventory-category.edit',
                'inventory-category.delete',
                'inventory-item.view',
                'inventory-item.create',
                'inventory-item.edit',
                'inventory-item.delete',
                'inventory-item.scan',
                'stock-receipt.view',
                'stock-receipt.create',
                'stock-issue.view',
                'stock-issue.create',
                'stock-return.view',
                'stock-return.create',
                'stock-transfer.view',
                'stock-transfer.create',
                'stock-adjustment.view',
                'stock-adjustment.create',
                'stock-adjustment.approve',
                'inventory-ledger.view',
                'stock-quarantine.manage',
                'stock-expiry.manage',
                'stock-damage.manage',
                'supplier.view',
                'supplier.create',
                'supplier.edit',
                'supplier.delete',
                'requisition.view',
                'requisition.create',
                'requisition.edit',
                'requisition.submit',
                'requisition.approve',
                'requisition.reject',
                'requisition.cancel',
                'procurement-approval.view',
                'purchase-order.view',
                'purchase-order.create',
                'purchase-order.edit',
                'purchase-order.issue',
                'purchase-order.cancel',
                'purchase-order.close',
                'goods-receipt.view',
                'goods-receipt.create',
                'goods-receipt.process',
                'maintenance.view',
                'maintenance.manage',
                'maintenance.fit-certify',
                'calibrations.manage',
                'faults.report',
                'reports.view',
                'reports.export',
                'audit-logs.view',
                'settings.view',
                'settings.update',
            ],
            'Burn Center Manager / Department Head' => [
                'dashboard.view',
                'departments.view',
                'locations.view',
                'asset-category.view',
                'asset.view',
                'asset-tag.view',
                'asset.scan',
                'asset-issue.view',
                'asset-return.view',
                'asset-transfer.view',
                'asset-history.view',
                'asset-status.change',
                'assets.view',
                'inventory-item.view',
                'inventory-item.scan',
                'stock-receipt.view',
                'stock-issue.view',
                'stock-return.view',
                'stock-transfer.view',
                'stock-adjustment.view',
                'inventory-ledger.view',
                'requisition.view',
                'requisition.create',
                'requisition.submit',
                'requisition.approve',
                'requisition.reject',
                'procurement-approval.view',
                'purchase-order.view',
                'goods-receipt.view',
                'maintenance.view',
                'faults.report',
                'reports.view',
            ],
            'Store Manager / Inventory Officer' => [
                'dashboard.view',
                'departments.view',
                'locations.view',
                'asset-category.view',
                'asset.view',
                'asset-tag.view',
                'asset.scan',
                'asset-history.view',
                'assets.view',
                'inventory-category.view',
                'inventory-category.create',
                'inventory-category.edit',
                'inventory-item.view',
                'inventory-item.create',
                'inventory-item.edit',
                'inventory-item.scan',
                'stock-receipt.view',
                'stock-receipt.create',
                'stock-issue.view',
                'stock-issue.create',
                'stock-return.view',
                'stock-return.create',
                'stock-transfer.view',
                'stock-transfer.create',
                'stock-adjustment.view',
                'stock-adjustment.create',
                'stock-adjustment.approve',
                'inventory-ledger.view',
                'stock-quarantine.manage',
                'stock-expiry.manage',
                'stock-damage.manage',
                'supplier.view',
                'requisition.view',
                'requisition.create',
                'requisition.submit',
                'procurement-approval.view',
                'goods-receipt.view',
                'goods-receipt.create',
                'goods-receipt.process',
                'reports.view',
                'reports.export',
            ],
            'Biomedical Engineer' => [
                'dashboard.view',
                'departments.view',
                'locations.view',
                'asset-category.view',
                'asset.view',
                'asset.edit',
                'asset-tag.view',
                'asset-tag.generate',
                'asset-tag.print',
                'asset-tag.regenerate',
                'asset.scan',
                'asset-transfer.view',
                'asset-transfer.create',
                'asset-history.view',
                'asset-status.change',
                'assets.view',
                'assets.update',
                'assets.transfer',
                'asset-labels.generate',
                'asset-labels.print',
                'maintenance.view',
                'maintenance.manage',
                'maintenance.fit-certify',
                'calibrations.manage',
                'faults.report',
                'reports.view',
            ],
            'Nurse Supervisor' => [
                'dashboard.view',
                'departments.view',
                'locations.view',
                'asset.view',
                'asset-tag.view',
                'asset.scan',
                'asset-issue.view',
                'asset-issue.create',
                'asset-return.view',
                'asset-return.create',
                'asset-transfer.view',
                'asset-transfer.create',
                'asset-history.view',
                'assets.view',
                'assets.assign',
                'assets.return',
                'inventory-item.view',
                'inventory-item.scan',
                'stock-return.view',
                'stock-return.create',
                'requisition.view',
                'requisition.create',
                'requisition.submit',
                'faults.report',
                'reports.view',
            ],
            'Staff Nurse / Clinical User' => [
                'dashboard.view',
                'asset.view',
                'asset.scan',
                'assets.view',
                'inventory-item.view',
                'inventory-item.scan',
                'requisition.create',
                'faults.report',
            ],
            'Pharmacist / Medical Store Staff' => [
                'dashboard.view',
                'departments.view',
                'locations.view',
                'asset-category.view',
                'asset.view',
                'asset-tag.view',
                'asset.scan',
                'assets.view',
                'inventory-category.view',
                'inventory-category.create',
                'inventory-category.edit',
                'inventory-item.view',
                'inventory-item.create',
                'inventory-item.edit',
                'inventory-item.scan',
                'stock-receipt.view',
                'stock-receipt.create',
                'stock-issue.view',
                'stock-issue.create',
                'stock-return.view',
                'stock-return.create',
                'stock-transfer.view',
                'stock-transfer.create',
                'stock-adjustment.view',
                'stock-adjustment.create',
                'inventory-ledger.view',
                'stock-quarantine.manage',
                'stock-expiry.manage',
                'stock-damage.manage',
                'supplier.view',
                'goods-receipt.view',
                'goods-receipt.create',
                'goods-receipt.process',
                'reports.view',
                'reports.export',
            ],
            'Procurement Officer' => [
                'dashboard.view',
                'asset-category.view',
                'asset.view',
                'supplier.view',
                'supplier.create',
                'supplier.edit',
                'supplier.delete',
                'requisition.view',
                'requisition.create',
                'requisition.edit',
                'requisition.submit',
                'procurement-approval.view',
                'purchase-order.view',
                'purchase-order.create',
                'purchase-order.edit',
                'purchase-order.issue',
                'purchase-order.cancel',
                'purchase-order.close',
                'goods-receipt.view',
                'goods-receipt.create',
                'goods-receipt.process',
                'reports.view',
                'reports.export',
            ],
            'Accounts / Finance' => [
                'dashboard.view',
                'asset-category.view',
                'asset.view',
                'asset-history.view',
                'inventory-item.view',
                'inventory-ledger.view',
                'supplier.view',
                'requisition.view',
                'procurement-approval.view',
                'purchase-order.view',
                'goods-receipt.view',
                'reports.view',
                'reports.export',
            ],
            'Auditor' => [
                'dashboard.view',
                'departments.view',
                'locations.view',
                'asset-category.view',
                'asset.view',
                'asset-tag.view',
                'asset.scan',
                'asset-issue.view',
                'asset-return.view',
                'asset-transfer.view',
                'asset-history.view',
                'assets.view',
                'inventory-category.view',
                'inventory-item.view',
                'inventory-item.scan',
                'stock-receipt.view',
                'stock-issue.view',
                'stock-return.view',
                'stock-transfer.view',
                'stock-adjustment.view',
                'inventory-ledger.view',
                'supplier.view',
                'requisition.view',
                'procurement-approval.view',
                'purchase-order.view',
                'goods-receipt.view',
                'reports.view',
                'reports.export',
                'audit-logs.view',
            ],
        ];
    }
}
